export const SITE = {
  title: 'SavePoint Guides',
  description:
    'Trending game guides for hot Steam releases — builds, boss strategies, and buying advice updated for what players are searching right now.',
  url: 'https://savepointguides.com',
  author: 'SavePoint Guides Team',
  locale: 'en_US',
} as const;

export const GAMES = {
  'meccha-chameleon': {
    title: 'Meccha Chameleon',
    description:
      'Hide-and-seek strategies, map spots, seeker tips, and settings for the 2026 Steam breakout hit.',
    steamUrl: 'https://store.steampowered.com/app/4704690/MECCHA_CHAMELEON/',
    affiliateLabel: 'Buy Meccha Chameleon on Steam',
    trending: true,
    trendingOrder: 1,
    releaseDate: '2026-06-09',
    steamAppId: 4704690,
    coverUrl: '/images/games/meccha-chameleon.jpg',
    heroCoverUrl: '/images/games/meccha-chameleon-hero.jpg',
    accentFrom: '#22c55e',
    accentTo: '#a855f7',
  },
  'path-of-exile-2': {
    title: 'Path of Exile 2',
    description:
      'Starter builds, act leveling routes, currency tips, and boss guides for PoE2.',
    steamUrl: 'https://store.steampowered.com/app/2694490/Path_of_Exile_2/',
    affiliateLabel: 'Buy Path of Exile 2 on Steam',
    trending: true,
    trendingOrder: 2,
    releaseDate: '2024-12-06',
    steamAppId: 2694490,
    accentFrom: '#b45309',
    accentTo: '#1c1917',
  },
  'cyberpunk-2077': {
    title: 'Cyberpunk 2077',
    description:
      'Patch 2.x builds, Phantom Liberty guides, cyberware picks, and PC settings.',
    steamUrl: 'https://store.steampowered.com/app/1091500/Cyberpunk_2077/',
    affiliateLabel: 'Buy Cyberpunk 2077 on Steam',
    trending: true,
    trendingOrder: 3,
    releaseDate: '2020-12-10',
    steamAppId: 1091500,
    accentFrom: '#fcee0a',
    accentTo: '#00f0ff',
  },
  'dead-by-daylight': {
    title: 'Dead by Daylight',
    description:
      'Survivor perks, killer guides, looping tips, and bloodpoint farming for DbD.',
    steamUrl: 'https://store.steampowered.com/app/381210/Dead_by_Daylight/',
    affiliateLabel: 'Buy Dead by Daylight on Steam',
    trending: true,
    trendingOrder: 4,
    releaseDate: '2016-06-14',
    steamAppId: 381210,
    accentFrom: '#dc2626',
    accentTo: '#111827',
  },
  'marvel-rivals': {
    title: 'Marvel Rivals',
    description:
      'Hero tier lists, team comps, role guides, and ability combos for Marvel Rivals.',
    steamUrl: 'https://store.steampowered.com/app/2767030/Marvel_Rivals/',
    affiliateLabel: 'Play Marvel Rivals on Steam',
    trending: true,
    trendingOrder: 5,
    releaseDate: '2024-12-06',
    steamAppId: 2767030,
    accentFrom: '#2563eb',
    accentTo: '#dc2626',
  },
  'forza-horizon-6': {
    title: 'Forza Horizon 6',
    description:
      'Best starter cars, credit farming, drift tuning, and festival guides for FH6.',
    steamUrl: 'https://store.steampowered.com/app/2483190/Forza_Horizon_6/',
    affiliateLabel: 'Buy Forza Horizon 6 on Steam',
    trending: true,
    trendingOrder: 6,
    releaseDate: '2026-05-27',
    steamAppId: 2483190,
    steamCardImage: 'hero' as const,
    steamHeroImage: 'hero' as const,
    steamThumbImage: 'hero' as const,
    accentFrom: '#2563eb',
    accentTo: '#f59e0b',
  },
  'baldurs-gate-3': {
    title: "Baldur's Gate 3",
    description:
      'Act 1 walkthroughs, best classes, companion guides, and build tips for BG3.',
    steamUrl: 'https://store.steampowered.com/app/1086940/Baldurs_Gate_3/',
    affiliateLabel: "Buy Baldur's Gate 3 on Steam",
    trending: true,
    trendingOrder: 7,
    releaseDate: '2023-08-03',
    steamAppId: 1086940,
    accentFrom: '#b45309',
    accentTo: '#7c2d12',
  },
  'elden-ring': {
    title: 'Elden Ring',
    description:
      'Starter weapons, ashes of war, boss routes, and open-world progression for Elden Ring.',
    steamUrl: 'https://store.steampowered.com/app/1245620/ELDEN_RING/',
    affiliateLabel: 'Buy Elden Ring on Steam',
    trending: true,
    trendingOrder: 8,
    releaseDate: '2022-02-25',
    steamAppId: 1245620,
    accentFrom: '#ca8a04',
    accentTo: '#1c1917',
  },
  'palworld': {
    title: 'Palworld',
    description:
      'Best Pals, base building, breeding tips, and early-game survival for Palworld.',
    steamUrl: 'https://store.steampowered.com/app/1623730/Palworld/',
    affiliateLabel: 'Buy Palworld on Steam',
    trending: true,
    trendingOrder: 9,
    releaseDate: '2024-01-19',
    steamAppId: 1623730,
    accentFrom: '#3b82f6',
    accentTo: '#22c55e',
  },
  'helldivers-2': {
    title: 'Helldivers 2',
    description:
      'Best loadouts, stratagem combos, armor picks, and mission survival for Helldivers 2.',
    steamUrl: 'https://store.steampowered.com/app/553850/HELLDIVERS_2/',
    affiliateLabel: 'Buy Helldivers 2 on Steam',
    trending: true,
    trendingOrder: 10,
    releaseDate: '2024-02-08',
    steamAppId: 553850,
    accentFrom: '#fbbf24',
    accentTo: '#1e3a5f',
  },
  'black-myth-wukong': {
    title: 'Black Myth: Wukong',
    description:
      'Combat stances, spells, transformations, and boss strategies for Black Myth: Wukong.',
    steamUrl: 'https://store.steampowered.com/app/2358720/Black_Myth_Wukong/',
    affiliateLabel: 'Buy Black Myth: Wukong on Steam',
    trending: true,
    trendingOrder: 11,
    releaseDate: '2024-08-20',
    steamAppId: 2358720,
    accentFrom: '#dc2626',
    accentTo: '#fbbf24',
  },
  'hades-ii': {
    title: 'Hades II',
    description:
      'Weapon aspects, boon synergies, keepsakes, and escape route tips for Hades II.',
    steamUrl: 'https://store.steampowered.com/app/1145350/Hades_II/',
    affiliateLabel: 'Buy Hades II on Steam',
    trending: true,
    trendingOrder: 12,
    releaseDate: '2024-05-06',
    steamAppId: 1145350,
    accentFrom: '#7c3aed',
    accentTo: '#1e1b4b',
  },
  'stardew-valley': {
    title: 'Stardew Valley',
    description:
      'First-year plans, best crops, money tips, and community center guides for Stardew.',
    steamUrl: 'https://store.steampowered.com/app/413150/Stardew_Valley/',
    affiliateLabel: 'Buy Stardew Valley on Steam',
    trending: true,
    trendingOrder: 13,
    releaseDate: '2016-02-26',
    steamAppId: 413150,
    accentFrom: '#22c55e',
    accentTo: '#84cc16',
  },
  'monster-hunter-wilds': {
    title: 'Monster Hunter Wilds',
    description:
      'Weapon guides, armor skills, hunt strategies, and progression for Monster Hunter Wilds.',
    steamUrl: 'https://store.steampowered.com/app/2246340/Monster_Hunter_Wilds/',
    affiliateLabel: 'Buy Monster Hunter Wilds on Steam',
    trending: true,
    trendingOrder: 14,
    releaseDate: '2025-02-28',
    steamAppId: 2246340,
    accentFrom: '#ea580c',
    accentTo: '#451a03',
  },
  'hogwarts-legacy': {
    title: 'Hogwarts Legacy',
    description:
      'Spell combos, talent picks, gear traits, and combat guides for Hogwarts Legacy.',
    steamUrl: 'https://store.steampowered.com/app/990080/Hogwarts_Legacy/',
    affiliateLabel: 'Buy Hogwarts Legacy on Steam',
    trending: true,
    trendingOrder: 15,
    releaseDate: '2023-02-10',
    steamAppId: 990080,
    accentFrom: '#7c3aed',
    accentTo: '#fbbf24',
  },
  'valheim': {
    title: 'Valheim',
    description:
      'Boss order, base locations, tool progression, and biome guides for Valheim.',
    steamUrl: 'https://store.steampowered.com/app/892970/Valheim/',
    affiliateLabel: 'Buy Valheim on Steam',
    trending: true,
    trendingOrder: 16,
    releaseDate: '2021-02-02',
    steamAppId: 892970,
    accentFrom: '#64748b',
    accentTo: '#22c55e',
  },
  'lethal-company': {
    title: 'Lethal Company',
    description:
      'Quota runs, ship upgrades, monster survival, and moon guides for Lethal Company.',
    steamUrl: 'https://store.steampowered.com/app/1966720/Lethal_Company/',
    affiliateLabel: 'Buy Lethal Company on Steam',
    trending: true,
    trendingOrder: 17,
    releaseDate: '2023-10-24',
    steamAppId: 1966720,
    accentFrom: '#f97316',
    accentTo: '#1c1917',
  },
  'red-dead-redemption-2': {
    title: 'Red Dead Redemption 2',
    description:
      'Best guns, camp upgrades, honor tips, and open-world guides for RDR2.',
    steamUrl: 'https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/',
    affiliateLabel: 'Buy Red Dead Redemption 2 on Steam',
    trending: true,
    trendingOrder: 18,
    releaseDate: '2019-12-05',
    steamAppId: 1174180,
    accentFrom: '#b91c1c',
    accentTo: '#78350f',
  },
  'counter-strike-2': {
    title: 'Counter-Strike 2',
    description:
      'Aim training, best settings, map callouts, and economy guides for CS2.',
    steamUrl: 'https://store.steampowered.com/app/730/CounterStrike_2/',
    affiliateLabel: 'Play Counter-Strike 2 on Steam',
    trending: true,
    trendingOrder: 19,
    releaseDate: '2023-09-27',
    steamAppId: 730,
    accentFrom: '#f59e0b',
    accentTo: '#1e3a5f',
  },
  'sons-of-the-forest': {
    title: 'Sons of the Forest',
    description:
      'Survival basics, Kelvin commands, base building, and cave guides for Sons of the Forest.',
    steamUrl: 'https://store.steampowered.com/app/1326470/Sons_Of_The_Forest/',
    affiliateLabel: 'Buy Sons of the Forest on Steam',
    trending: true,
    trendingOrder: 20,
    releaseDate: '2023-02-23',
    steamAppId: 1326470,
    accentFrom: '#166534',
    accentTo: '#1c1917',
  },
  'satisfactory': {
    title: 'Satisfactory',
    description:
      'Factory layouts, power generation, tier progression, and optimization for Satisfactory.',
    steamUrl: 'https://store.steampowered.com/app/526870/Satisfactory/',
    affiliateLabel: 'Buy Satisfactory on Steam',
    trending: true,
    trendingOrder: 21,
    releaseDate: '2024-09-10',
    steamAppId: 526870,
    accentFrom: '#f97316',
    accentTo: '#eab308',
  },
  'rust': {
    title: 'Rust',
    description:
      'Wipe survival, base building, raid defense, and PvP weapon guides for Rust.',
    steamUrl: 'https://store.steampowered.com/app/252490/Rust/',
    affiliateLabel: 'Buy Rust on Steam',
    trending: true,
    trendingOrder: 22,
    releaseDate: '2018-02-08',
    steamAppId: 252490,
    accentFrom: '#dc2626',
    accentTo: '#57534e',
  },
  'terraria': {
    title: 'Terraria',
    description:
      'Boss order, pre-Hardmode weapons, NPC housing, and progression for Terraria.',
    steamUrl: 'https://store.steampowered.com/app/105600/Terraria/',
    affiliateLabel: 'Buy Terraria on Steam',
    trending: true,
    trendingOrder: 23,
    releaseDate: '2011-05-16',
    steamAppId: 105600,
    accentFrom: '#3b82f6',
    accentTo: '#22c55e',
  },
  'ark-survival-ascended': {
    title: 'Ark: Survival Ascended',
    description:
      'Early tames, base locations, engram priorities, and survival for Ark ASA.',
    steamUrl: 'https://store.steampowered.com/app/2399830/ARK_Survival_Ascended/',
    affiliateLabel: 'Buy Ark: Survival Ascended on Steam',
    trending: true,
    trendingOrder: 24,
    releaseDate: '2023-10-25',
    steamAppId: 2399830,
    accentFrom: '#0ea5e9',
    accentTo: '#166534',
  },
  'the-finals': {
    title: 'The Finals',
    description:
      'Class loadouts, map strategies, gadget combos, and ranked tips for The Finals.',
    steamUrl: 'https://store.steampowered.com/app/2073850/THE_FINALS/',
    affiliateLabel: 'Play The Finals on Steam',
    trending: true,
    trendingOrder: 25,
    releaseDate: '2023-12-07',
    steamAppId: 2073850,
    accentFrom: '#ef4444',
    accentTo: '#fbbf24',
  },
  'dark-souls-iii': {
    title: 'Dark Souls III',
    description:
      'Best weapons, boss order, infusion tips, and beginner survival for Dark Souls 3.',
    steamUrl: 'https://store.steampowered.com/app/374320/DARK_SOULS_III/',
    affiliateLabel: 'Buy Dark Souls III on Steam',
    trending: true,
    trendingOrder: 26,
    releaseDate: '2016-04-11',
    steamAppId: 374320,
    accentFrom: '#6b7280',
    accentTo: '#fbbf24',
  },
} as const;

export type GameSlug = keyof typeof GAMES;

export type GameMeta = (typeof GAMES)[GameSlug];
